### ISSUE TITLE
Feature request: the ability to turn off density dependence

### ISSUE THREAD

**Issue by josephwb** [macroevolution/bamm#135]
Seems like an obvious question one could ask is "what is the signal for density dependence?", which could be assessed by running the analysis with and without that parameter. In addition, could allow comparison to programs that do not employ the parameter (say, MEDUSA).

**Comment by blackrim** [comment]
I concur. In addition to simply testing for signal of density dependence, it would be beneficial to be able to determine if the difference in results using different methods are the result of different models or methods. As @josephwb mentions, if MEDUSA finds different shifts, is it the result of the MEDUSA employing stepwise, or is it because MEDUSA doesn't include density dependence.

**Comment by drabosky** [comment]
It is trivial to turn off the temporal variation in rates. Just set: 
updateRateLambdaShift = 0
in the control file, and make sure
lambdaShiftInit = 0

and you run a MEDUSA like analysis. However, the likelihoods for MEDUSA and BAMM are not the same, and the way they deal with incomplete sampling is not the same. Different likelihood for this part. Hence, if you specify incomplete sampling fractions in BAMM, I would be surprised if you get the same results, at least if your tree is fairly incomplete (< 50% taxa sampled)

**Comment by drabosky** [comment]
more formally, for some terminal branch or clade in the tree:
BAMM likelihood = likelihood of the tree, e.g., distribution of times and speciation events, given the sampling level
MEDUSA likelihood = likelihood obtaining N species after some amount of time T. 

My intuition is that if you integrate the BAMM likelihood over all possible topologies and branch lengths that are consistent with a tree of age T and N species, you will get the same thing. But I haven't proved it. (FYI, the likelihood used in BAMM with incomplete sampling is the same as for BiSSE etc and follows from Nee et al 1994 and earlier work)

**Comment by drabosky** [comment]
Final comment here would be the ability to use Bayes factors to compare the model with time variation turned off to the MEDUSA like model

In some ways, this will be superseded, because the "time-flip" model does exactly what you want to do in some ways - rate shifts can be either time-dependent versus constant-rate processes and these 2 alternatives are sampled in proportion to their posterior probability. See documentation on this option on website - we've implemented and tested it extensively but haven't published it yet.

**Comment by blackrim** [comment]
OK, will check this out.

**Comment by josephwb** [comment]
Oh, that is easy! Maybe not obvious? (No one here knew that).

BTW, the MEDUSA likelihood uses your 2007 equation (i.e. distribution of times and speciation events); e.g. altering internal node ages while keeping the root age constant will give you different likelihoods, so it is not just the likelihood obtaining N species after some amount of time T. The incomplete sampling is clearly way different though.

**Comment by drabosky** [comment]
Yeah, MEDUSA uses the "topology" birth-death process but only for the backbone. And it's an updated equation because there's an error in the equation for the backbone in my paper (you guys corrected this earlier). The tip likelihood (with incomplete sampling) is what I describe above. The MEDUSA model is a hybrid of the two models applied to different parts of the tree. Honestly, it would be better to go back to this approach for BAMM for the modeling of highly incomplete data, until a better solution is found (e.g. using PASTIS to add missing species within the incompletely sampled clades)

**Comment by josephwb** [comment]
I guess I will close this, although it would be nice to explicitly state this stuff somewhere. The updateRateLambdaShift parameter is described [here](http://bamm-project.org/configuration.html#id4), but it is not obvious that setting it to 0 (or that the concommital setting lambdaShiftInit also to 0) will bring about the desired configuration.

I think actually having something like:
```
timeVariableRates = false
```
in the control file would be nicer.

**Comment by drabosky** [comment]
Just to be clear, the MEDUSA like model) and constraining models from BAMM to less-complex submodels are all described here on the advanced options page:

http://bamm-project.org/advanced.html#modeling-less-complex-evolutionary-scenarios

but we could make this more prominent somehow I guess
